### ISSUE TITLE
Pipewire support

### ISSUE THREAD

**Issue by Gr33nEyes** [tx00100xt/SeriousSamClassic#11]
Will you add support Pipewire?

**Comment by tx00100xt** [comment]
SDL2 Audio has pipeware support.
https://www.phoronix.com/news/SDL2-Lands-PipeWire-Audio

Start the game with:
>SDL_AUDIODRIVER=pipewire
>

https://wiki.libsdl.org/SDL2/FAQUsingSDL#how_do_i_choose_a_specific_audio_driver

It is worth considering that the pipewire is still under active development, so there may be some problems with the sound due to the fault of the pipeware.

https://wiki.gentoo.org/wiki/PipeWire

**Comment by Gr33nEyes** [comment]
In my Arch Linux Pipewire is default

**Comment by tx00100xt** [comment]
I answered. SDL2 library, which is used in the game - also supports pipeware alsa oss pulseaudio.
Run game with command "SDL_AUDIODRIVER=pipewire ./SeriousSam"

**Comment by tx00100xt** [comment]
Since the SDL2 library used in the game supports pipeware, I close the issue.
