### ISSUE TITLE
Graphics are messed up

### ISSUE THREAD

**Issue by TheBrainScrambler** [tx00100xt/SeriousSamClassic#17]
![serioussam-screwed](https://github.com/tx00100xt/SeriousSamClassic/assets/34945377/1d8494c0-d002-49f3-bd88-76843b398ae8)

Basically this.

Here are the logs: [SeriousSam.log](https://github.com/tx00100xt/SeriousSamClassic/files/12329801/SeriousSam.log)

An interesting line in here could be this one:
```
unable to setup OpenGL settings list: Cannot open file `/home/user/.local/share/Serious-Engine/serioussam/Scripts/GLSettings/GLSettings.lst' (No such file or directory) ()
```

Don't know if it's related, and don't know how I'm supposed to have this file.

To give more context to it, I am trying to port Serious Sam to NixOS. I don't know if this graphic mess is caused by that or if it is related to my computer.

NixOS is speclal in that there are no global paths like /usr/bin or /usr/lib to put binaries and libraries, instead they are all in their own folders. SDL2 libs for example are in `/nix/store/ys75kpw9nn0ydbxm2w7wi1gd0bl1s0cv-SDL2-2.28.1/lib` for me.

```
ls /nix/store/ys75kpw9nn0ydbxm2w7wi1gd0bl1s0cv-SDL2-2.28.1/lib
libSDL2-2.0.so.0  libSDL2-2.0.so.0.2800.1  libSDL2.la  libSDL2main.la  libSDL2.so  libSDL2_test.la
```

Since your CMakeFile and the code assumed global paths for a system install it was a bit painful but I patched around.

Here is my nix file for building it and patches it needed. The nix file explains how to build the package from source, it's like a PKGBUILD for Arch Linux.
[serioussam.tgz](https://github.com/tx00100xt/SeriousSamClassic/files/12329795/serioussam.tgz)

If you want to reproduce this, Nix is a cross-platform package manager, you can check out https://nixos.org/download.

To build it with Nix, put the files from serioussam.tgz in some directory, cd into this directory and do this:
`nix-build -E 'with import <nixpkgs> {}; callPackage ./serioussam.nix {}'`

If you need more info please tell me.

**Comment by tx00100xt** [comment]
Hello.
Looking at the log, I saw two problems.
The first problem is the lack of necessary files,. Since the directory "/home/user/.local/share/Serious-Engine/serioussam/" is assigned to the date, the data files must also be there. All the necessary files except gro files and levels are in the repository. You can just copy them from the repository:
```
git clone https://github.com/tx00100xt/SeriousSamClassic.git
cd SeriousSamClassic
cp -ax SamTFE/* ~/.local/share/Serious-Engine/serioussam
cp -ax SamTSE/* ~/.local/share/Serious-Engine/serioussamse
rm -rf ~/.local/share/Serious-Engine/serioussam/{Tools.Win32,Sources,serioussam.desktop,serioussam.png}
rm -rf ~/.local/share/Serious-Engine/serioussamse/{Tools.Win32,Sources,serioussamse.desktop,serioussamse.png}
```
Most likely, it was precisely because of the lack of the necessary game settings files that there were problems with displaying graphics.

The second problem is that the libvorbisfile.so.3 library was not found. Ogg files will not play. There will be no music in the game.  Libraries open here:
https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTFE/Sources/Engine/Base/Unix/UnixDynamicLoader.cpp#L65

**Comment by TheBrainScrambler** [comment]
> Hello. Looking at the log, I saw two problems. The first problem is the lack of necessary files,. Since the directory "/home/user/.local/share/Serious-Engine/serioussam/" is assigned to the date, the data files must also be there. All the necessary files except gro files and levels are in the repository. You can just copy them from the repository:
> 
> ```
> git clone https://github.com/tx00100xt/SeriousSamClassic.git
> cd SeriousSamClassic
> cp -ax SamTFE/* ~/.local/share/Serious-Engine/serioussam
> cp -ax SamTSE/* ~/.local/share/Serious-Engine/serioussamse
> rm -rf ~/.local/share/Serious-Engine/serioussam/{Tools.Win32,Sources,serioussam.desktop,serioussam.png}
> rm -rf ~/.local/share/Serious-Engine/serioussamse/{Tools.Win32,Sources,serioussamse.desktop,serioussamse.png}
> ```
> 
> Most likely, it was precisely because of the lack of the necessary game settings files that there were problems with displaying graphics.

Oh where was this documented ?
The error with the OpenGL settings missing went away, but ... It still doesn't work, my graphics still look like the picture above.

Logs this time: [SeriousSam.log](https://github.com/tx00100xt/SeriousSamClassic/files/12330258/SeriousSam.log)

> The second problem is that the libvorbisfile.so.3 library was not found. Ogg files will not play. There will be no music in the game. Libraries open here: https://github.com/tx00100xt/SeriousSamClassic/blob/main/SamTFE/Sources/Engine/Base/Unix/UnixDynamicLoader.cpp#L65

I know about this problem. I also know how to fix it, I was just focusing on the broken graphics right now. I didn't want to fix sound now because I would have to recompile again the engine.

**Comment by tx00100xt** [comment]
> Oh where was this documented ?

Initially, it was assumed that the launch of the game will from a cloned repository. Therefore, the settings files and scripts were added to the root directory of the game, and there was no need to copy them. The ability to locate data, libraries and executable files in a different directory was added later, in order to be able to install the game on the system using the standard Linux paths. In this case, you need to copy the all content (data) from the CD or GOG version to the directory where the data is located.

About graphics:
It can be seen from the log that the HD Graphics 3000 graphics built into the Sandy Bridge family processor is used. Unfortunately, I have no way to test it.
The launch of the game was tested on a fairly large number of video adapters from nvidia (GT4xx-RTX3xxx) and amd (HD series, RX series, amd processors with graphics), and no such problems were observed anywhere.

**Comment by tx00100xt** [comment]
Hello.
I installed the ready image from here:
https://nixos.org/download#nixos-virtualbox
Build from serioussam.tgz
Everything works well. There are no problems with graphics.
![Снимок экрана в 2023-10-08 23-03-22](https://github.com/tx00100xt/SeriousSamClassic/assets/105300480/5d3bcbc0-8673-4b10-beda-fd8b448472c7)
![Снимок экрана в 2023-10-08 23-03-47](https://github.com/tx00100xt/SeriousSamClassic/assets/105300480/bef62500-dbc2-41ea-b7c4-b46031caca90)
![Снимок экрана в 2023-10-08 23-14-57](https://github.com/tx00100xt/SeriousSamClassic/assets/105300480/7acaa6a9-c453-4ac9-ac77-69ddeed68194)

**Comment by TheBrainScrambler** [comment]
Ok, it must be my computer then, thanks !

**Comment by TheBrainScrambler** [comment]
For posterity, graphics work now for me. Looks like 1.10.6 fixed it for me, it's just that I thought I had updated to 1.10.6 and that it still didn't work, but actually I was just using the same old version which caused me the graphics bugs.
