### ISSUE TITLE
Problems with RPi4

### ISSUE THREAD

**Issue by dragon99919** [tx00100xt/SeriousSamClassic#7]
The Raspberry Pi 4 build seems to have some problems... I'm on official RPiOS x64, the newest version.

First one if with the compiling itself - a line '`cat /proc/cpuinfo |grep vendor_id |wc -l`' returns 0 which throws the project out of the window after compiling ECC. This can be however easily fixed by changing the number there manually to '4', still, maybe worth of changing for RPI itself?

Second problem is when launching the compiled project, after execution of the compiled binary, terminal shows two lines and program ends:
`STUBBED: load window icon in /home/dragon99919/git/SeriousSamClassic/SamTSE/Sources/SeriousSam/MainWindow.cpp, line 167.
STUBBED: Need SDL invisible window or something in /home/dragon99919/git/SeriousSamClassic/SamTSE/Sources/SeriousSam/MainWindow.cpp, line 328.`

Any idea how to fix it by any chance?

**Comment by tx00100xt** [comment]
Of course there are ideas. Because there is an example of a successful launch of the game on raspberry pi 4 Ubuntu 22 lts (arm64). Full thread here: https://github.com/tx00100xt/SeriousSamClassic-VK/issues/3



> STUBBED: load window icon in /home/dragon99919/git/SeriousSamClassic/SamTSE/Sources/SeriousSam/MainWindow.cpp, line 167. STUBBED: Need SDL invisible window or something in /home/dragon99919/git/SeriousSamClassic/SamTSE/Sources/SeriousSam/MainWindow.cpp, line 328.
>
This is an information message from the port of Ryan Gordon. It does not affect the launch of the game. The game always has these messages at startup. Since the game used to run on the Raspberry Pi 4, it's possible that recent commits caused launch errors.
The first thing to try is to enable SINGLE_THREAD.
To do this, you need a line in CMakeLists.txt:
>option(USE_SINGLE_THREAD "Use Single Threaded Version" FALSE) 
>
replace with
>option(USE_SINGLE_THREAD "Use Single Threaded Version" TRUE)
>
Second - you can try to rollback to the old git commit:
>git clone https://github.com/tx00100xt/SeriousSamClassic.git
>cd SeriousSamClassic
>git checkout f4e66dce65fc3cc0c645cf67213f4f1caf9945a8
>
for SeriousSamClassic repo.
>git clone https://github.com/tx00100xt/SeriousSamClassic-VK.git
>cd SeriousSamClassic-VK
>git checkout 40bfc9a0cebc5a49a371d99d1164502f2de28b7f
>
for SeriousSamClassic-VK repo.

And it is also desirable to attach the game log to make it clearer. 
(.local/share/Serious-Engine/serioussamse/SeriousSam.log iin latest version,  or SeriousSam.log in the game directory in previous versions)

**Comment by tx00100xt** [comment]
Fixed building scrips.
https://github.com/tx00100xt/SeriousSamClassic/commit/013c7187738fc9aab87a727add234026704dbcde
https://github.com/tx00100xt/SeriousSamClassic-VK/commit/98dd388de7f186d57532efafd93c012f35950981

**Comment by dragon99919** [comment]
Okay, actually Log told me everything I should've known. : )
There were missing Class files. After copying the gros from the base game, it launched without a problem.
Thanks a lot for help!

**Comment by tx00100xt** [comment]
This is good. Then I think the issue can be closed.
